Update postalcode and store structure.
quatro32/MarioPizzaImport pull request #4
Opened 2021-03-21 13:58 UTC by FNG21

2021-03-21 15:09 UTC, Alduthir requested changes

2021-03-21 15:09 UTC, Alduthir commented on MarioPizzaImport/Logger.cs
> +            this.SaveLog("CORRECTION", fileName, string.Format("Corrected {0} to {1} during import.", stringInput, stringCorrected));
Als ik het goed begrijp moeten we dus Error gebruiken in de plaats van exceptions throwen. En als we aan de hand van de mapping iets corrigeren moeten we daar ook een Correction log voor maken? 
Netjes dan hebben we iig een volledige log. Ook van als het wel goed ging!

2021-03-21 15:09 UTC, Alduthir commented on MarioPizzaImport/Logger.cs
> +            command.Parameters.Add(parameterErrorString);
Ik mis 1 ding in de logs eigenlijk en dat is een dateTime van wanneer hij gelogged is. 
Dan kun je iig nog onderscheid maken van oh dit was de output van vandaag of die van 3 weken geleden. Of truncaten we de logtabel elke keer als er een import gedraait wordt?

2021-03-21 15:09 UTC, Alduthir commented on MarioPizzaImport/Program.cs
> +            ////InsertExtraIngredients(@"C:\Users\shnva\Desktop\ingredienten.csv", database, countrycode);
Volgens mij uitgecomment i.v.m. testen, maar ze graag wel weer ff aanzetten voordat we dit mergen.

2021-03-21 15:09 UTC, Alduthir commented on MarioPizzaImport/Program.cs
> -        static void InsertExtraIngredients(string path, dbi298845_prangersEntities db, countrycode countrycode)
Er stonden 2 InsertExtraIngredients functies in de code. Dus ik snap dat er één van weggehaald is. 
Echter stond in 1 van de twee functies price= amount. Terwijl in de andere een fatsoenlijke regex gedraaid werdt voorde price. 

Lijkt er op alsof dus de verkeerde is weggegooid, maar dat kan ook aan mij liggen.

2021-03-21 15:09 UTC, Alduthir commented on MarioPizzaImport/StoreImporter.cs
> +        // TODO: Would be nice to use the mapping table for this.
Dat kan zeker. :) maar ik vindt een Dictionary ook netjes hoor.

2021-03-21 15:09 UTC, Alduthir commented on MarioPizzaImport/StoreImporter.cs
> +                                Console.WriteLine("Couldn't import store {0}", allLineStoreInformation[0]);
Zou je dan juist niet hier netjes je Logger ERROR voor gebruiken?

2021-03-21 15:14 UTC, FNG21 commented on MarioPizzaImport/App.config
> +	  <add name="dbi298845_prangersEntities" connectionString="metadata=res://*/MarioPizzaModel.csdl|res://*/MarioPizzaModel.ssdl|res://*/MarioPizzaModel.msl;provider=System.Data.SqlClient;provider conn
Already fixed, is juist de connectie naar de remote database ipv de lokale SQLExpress variant

2021-03-21 15:15 UTC, FNG21 commented on MarioPizzaImport/Logger.cs
> +            command.Parameters.Add(parameterErrorString);
Good catch, maar dit wordt automatisch gedaan door de stored procedure ;) (Die code zou nu ook in de PR moeten zitten)

2021-03-21 15:15 UTC, FNG21 commented on MarioPizzaImport/Program.cs
> +            ////InsertExtraIngredients(@"C:\Users\shnva\Desktop\ingredienten.csv", database, countrycode);
Yep, was nog draft, is al fixed ;-)

2021-03-21 15:16 UTC, FNG21 commented on MarioPizzaImport/StoreImporter.cs
> +        // TODO: Would be nice to use the mapping table for this.
dan houden we die zo ;-) (todo verwijderd)

2021-03-21 15:19 UTC, FNG21 commented on MarioPizzaImport/StoreImporter.cs
> +                                Console.WriteLine("Couldn't import store {0}", allLineStoreInformation[0]);
true, fixed

2021-03-21 15:21 UTC, FNG21 commented on MarioPizzaImport/Logger.cs
> +            this.SaveLog("CORRECTION", fileName, string.Format("Corrected {0} to {1} during import.", stringInput, stringCorrected));
Inderdaad, als iets niet lukt doen we `LogError` en throw Exception() (mits we execution willen stoppen)
Als iets wel lukt, maar we hebben iets gecorrigeerd doen we idd `LogCorrection` zodat we in de log een mooi overzicht hebben van alle "keuzes" die het systeem maakte :)

2021-03-21 15:23 UTC, FNG21 commented on MarioPizzaImport/Program.cs
> -        static void InsertExtraIngredients(string path, dbi298845_prangersEntities db, countrycode countrycode)
Je hebt gelijk, ,fixed :)

2021-03-22 10:20 UTC, Alduthir commented on MarioPizzaImport/Logger.cs
> +            command.Parameters.Add(parameterErrorString);
Netjes

2021-03-22 10:21 UTC, Alduthir commented on MarioPizzaImport/StoreImporter.cs
> +        // TODO: Would be nice to use the mapping table for this.
Sws nooit zo'n fan van TODO's in de code. Want t komt er vaak toch niet van haha.

2021-03-22 10:22 UTC, Alduthir approved these changes

2021-03-22 10:36 UTC, merged